FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["DataDownloader/DataDownloader.csproj", "DataDownloader/"]
RUN dotnet restore "DataDownloader/DataDownloader.csproj"
COPY . .
WORKDIR "/src/DataDownloader"
RUN dotnet build "DataDownloader.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DataDownloader.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "DataDownloader.dll"]
