version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    links:
      - redis
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
  data-caller:
    build: 
      context: .
      dockerfile: Dockerfile_data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
    depends_on:
      - api
      